### ISSUE TITLE
Move Solidity language design discussions to a dedicated forum

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity#10046]
## Updates / Latest Status

We've decided we want to set up a dedicated Solidity Forum based on Discourse.

**Task Tracker**
- [x] Define categories and write introductory texts - done, find it [here](https://docs.google.com/document/d/1THy4XIbeK90v7I7Q4lL4HTbG8EVRfsuVRw7MrTxGUKI/edit?usp=sharing)
- [x] Define guidelines of what will be discussed where etc (e.g. Github issues vs. mailing list vs. forum) 
- [x] Install Discourse: https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md - update: reached out to Devops to support with the hosting see https://github.com/ethereum/devops/issues/597
- [x] Set up Solidity Forum using Discourse
- [x] Promote forum via social channels 

## Current Situation

Most language design related topics are either discussed directly in the respective Github issues or in the solidity-users mailing list: https://groups.google.com/g/solidity-users.

These approaches are not really ideal since it's not very convenient to go back and understand past discussions and decisions. Also, there is no way to cluster the information (e.g. sort by a specific topic or category).

## Solution Idea

A forum would allow all language design related content to be in one place, even readable / accessible without an account. The introduction of a forum could also pave the way towards a potentially more structured language design process for the future.

Discourse seems to be the best open-source forum out there. 
Several well-known forums are based on Discourse: 
- Rust forum: https://internals.rust-lang.org/ and https://users.rust-lang.org/
- Go: https://forum.golangbridge.org/
- EIPs: https://eips.ethereum.org/
- Ethereum Magicians: https://ethereum-magicians.org/
- Eth Research: https://ethresear.ch/

Standard C++ and Go also have mailing lists:
- Go: https://groups.google.com/g/golang-nuts
- C++: https://lists.isocpp.org/mailman/listinfo.cgi/std-proposals

### Pros

Discoure comes with a lot of great features: https://www.discourse.org/features / https://github.com/discourse/discourse

Amongst others also the "reply via email" function: 
![image](https://user-images.githubusercontent.com/41991517/96119613-89fc8d80-0eed-11eb-8da5-943c46e0094d.png)

- Categories help cluster
- All conversations in one place and easy to browse
- Open and transparent discussions
- Could add possibilities for new subcategories to emerge, e.g. a category where Sol code snippets are discussed between power users etc.  

### Cons

- Mailing list could feel more committed; interaction on forum needs to be a push from the active users
- Moving all from the mailing list over to the forum could be tricky initially

**Please let me know what you generally think about this idea!**

**Comment by ekpyron** [comment]
In general I like the idea - discourse seems to be a nice platform for the job, so I'm generally in favor of this or something like this.
But maybe some more points to consider:
 - It will definitely involve maintenance effort - i.e. there are categories and clusters and all those features, but someone actually has to be behind categorizing and clustering stuff ;-), etc.
 - ``All conversations in one place and easy to browse`` - well, arguably that'd be github issues :-). I see that a platform like discourse has the huge advantage of having more social media integration, less of an account/login burden, i.e. a generally lower entry barrier (which by the way can also be an issue wrt eg spam etc - but I'd say it's more beneficial than harmful), etc. - but we will have duplication and the need to sync between github and such a discourse platform, which is also definitely non-zero effort.

Which basically boils down to: it'll probably be quite some work and will continue to be quite some work indefinitely - I myself find it rather hard to anticipate *how much* exactly (it may not be too bad, I'm not sure), but we should probably make sure that we're committed to it and up to it, because otherwise having such a platform and basically letting it rot around without interacting with it enough and without having it in sync with github would make things worse not better...

**Comment by ekpyron** [comment]
Also: maybe not all discussion should be public from the very beginning? I.e. bringing up and discussing an important bug with security experts on the mailing list might want to be kept "privileged" - there's probably a way to have a restricted category in discourse for that to which we grant access to basically the people in the mailing list? Does that work well or is it account chaos? Or would we just keep the mailing list for that? Not sure about any of that ;-).

**Comment by franzihei** [comment]
## Next Steps

- [ ] Define categories and write introductory texts
- [ ] Define guidelines of what will be discussed where etc (e.g. Github issues vs. mailing list vs. forum)
- [ ] Install Discourse: https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md
- [ ] Set up Solidity Forum using Discourse

**Comment by franzihei** [comment]
## Proposed Setup for the Forum. 

I'm proposing the following categories (as a start):

- **Announcements**: Low-traffic category for important announcements about the Solidity language and compiler.
- **Compiler**: Discussion and feedback about the compiler itself.
- **Code Wizards**: Get help with your Solidity code or share helpful tips or code snippets you came up with that are worth spreading.
- **Documentation**: Discussion about the documentation and its translations.
- **Language Design**: Proposals and discussion on new language features and their implementation.
- **Meta & Administration**: Discussion about this forum, its organizational structure, and how it can be improved.
- **Miscellaneous**

_Additional Categories (TBD)_

- **Community**: Information and discussion around community happenings such as events, hackathons, talks, meetups etc.
- **Jobs**: You may post Solidity-related Job opportunities here.
- **Tools & Infrastructure**: Discussion about dev tools and infrastructure.

### Read this to get started post

Welcome to the Solidity Forum! 

This is the place to discuss topics and questions related to…

- The implementation and design of Solidity programming language.
- The Solidity compiler. 
- Solidity tips and code snippets.
- Solidity documentation and its translation.
- Discussions and announcements about Solidity releases.

Please be aware that this is not the place for…

- Ad-hoc support questions. For urgent Solidity support questions, please use the Solidity Gitter chat.
- Solidity bugs, vulnerabilities or issues. To report a bug, please use the GitHub issues tracker and refer to this guide on how to report issues.
- Generic Ethereum discussion. For that visit r/ethereum.
- Ethereum research specific discussion. For that, please refer to the ethresear.ch forum.
- EIP specific discussion. For that visit the Ethereum Magicians forum.

Please note that by participating in this forum you agree to abide by the terms of our Contributor Code of Conduct. Posts that are not respectful, constructive, or off-topic will be removed. 

See source document [here](https://docs.google.com/document/d/1THy4XIbeK90v7I7Q4lL4HTbG8EVRfsuVRw7MrTxGUKI/edit#).

**Comment by franzihei** [comment]
Done! https://forum.soliditylang.org/ :)
