### ISSUE TITLE
[SMTChecker] Verify the Circles UBI contract

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10062]
Let's try to verify it. Made a fork which has the Zeppelin code without imports and SMT enabled here: https://github.com/axic/circles-contracts/tree/smt

- [x] Bug with private fields in multiple files (fixed by #10139)
- [x] Contract types #10141
- [x] Track simple branches better #10142
- [x] Bug with BMC #10144
- [x] Bug with variables touched by `assembly` https://github.com/ethereum/solidity/issues/10619

---

Status as of 15th December:
```solidity
Warning: This is a pre-release compiler version, please do not use it in production.

Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> Token.sol:171:31:
    |
171 |     ) public onlyHub returns (bool) {
    |                               ^^^^

Warning: Assertion checker does not support inline assembly.
  --> Address.sol:33:9:
   |
33 |         assembly { codehash := extcodehash(account) }
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
  --> Address.sol:57:28:
   |
57 |         (bool success, ) = recipient.call{ value: amount }("");
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> Address.sol:123:51:
    |
123 |         (bool success, bytes memory returndata) = target.call{ value: weiValue }(data);
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not support inline assembly.
   --> Address.sol:132:17:
    |
132 |                 assembly {
    |                 ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by leonardoalt** [comment]
Latest CHC output:
```
Warning: This is a pre-release compiler version, please do not use it in production.

Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> Token.sol:171:31:
    |
171 |     ) public onlyHub returns (bool) {
    |                               ^^^^

Warning: Assertion checker does not support inline assembly.
  --> Address.sol:33:9:
   |
33 |         assembly { codehash := extcodehash(account) }
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
  --> Address.sol:57:28:
   |
57 |         (bool success, ) = recipient.call{ value: amount }("");
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> Address.sol:123:51:
    |
123 |         (bool success, bytes memory returndata) = target.call{ value: weiValue }(data);
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not support inline assembly.
   --> Address.sol:132:17:
    |
132 |                 assembly {
    |                 ^ (Relevant source part starts here and spans across multiple lines).
```

Created https://github.com/ethereum/solidity/issues/10596 to support some inline assembly.
We can't really support `call` besides the invariants in the presence of reentrancy, which we already have. I recently noticed that `call` isn't supported in that case, but it should. Created https://github.com/ethereum/solidity/issues/10576 to track that.
In any case, I think implementing those is not necessary for this issue.
@axic can we close this then?

**Comment by axic** [comment]
There's also the `Hub.sol` file, which had more issues. It uses `Token.sol` so it was a good first step.

**Comment by axic** [comment]
Took me a good 20 minutes to run:
```
Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> circles-contracts/contracts/Token.sol:171:31:
    |
171 |     ) public onlyHub returns (bool) {
    |                               ^^^^

bash-3.2$ solc/solc circles-contracts/contracts/Hub.sol 
Warning: This is a pre-release compiler version, please do not use it in production.

Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> circles-contracts/contracts/Token.sol:171:31:
    |
171 |     ) public onlyHub returns (bool) {
    |                               ^^^^

Warning: Assertion checker does not support inline assembly.
  --> circles-contracts/contracts/Address.sol:33:9:
   |
33 |         assembly { codehash := extcodehash(account) }
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not support inline assembly.
   --> circles-contracts/contracts/Address.sol:132:17:
    |
132 |                 assembly {
    |                 ^ (Relevant source part starts here and spans across multiple lines).

Warning: CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
   --> circles-contracts/contracts/Hub.sol:277:43:
    |
277 |         for (uint i = 0; i < seen.length; i++) {
    |                                           ^^^

Warning: CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
   --> circles-contracts/contracts/Hub.sol:305:32:
    |
305 |         require(seen.length <= steps + 1, "Seen too many addresses");
    |                                ^^^^^^^^^

Warning: CHC: Underflow (resulting value less than 0) might happen here.
   --> circles-contracts/contracts/Hub.sol:309:36:
    |
309 |             delete validation[seen[i-1]];
    |                                    ^^^

Warning: CHC: Underflow (resulting value less than 0) might happen here.
   --> circles-contracts/contracts/Hub.sol:308:44:
    |
308 |         for (uint i = seen.length; i >= 1; i--) {
    |                                            ^^^

Warning: CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
   --> circles-contracts/contracts/Hub.sol:333:43:
    |
333 |         for (uint i = 0; i < srcs.length; i++) {
    |                                           ^^^

Warning: CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
  --> circles-contracts/contracts/Hub.sol:67:13:
   |
67 |             iter += 1;
   |             ^^^^^^^^^

Warning: BMC: Overflow (resulting value larger than 2**256 - 1) might happen here.
  --> circles-contracts/contracts/SafeMath.sol:98:21:
   |
98 |         uint256 c = a * b;
   |                     ^^^^^
Note: 
Note that some information is erased after the execution of loops.
You can re-introduce information using require().

Warning: BMC: Overflow (resulting value larger than 2**256 - 1) might happen here.
  --> circles-contracts/contracts/Hub.sol:67:13:
   |
67 |             iter += 1;
   |             ^^^^^^^^^
Note: 
Note that some information is erased after the execution of loops.
You can re-introduce information using require().

Warning: BMC: Overflow (resulting value larger than 2**256 - 1) might happen here.
  --> circles-contracts/contracts/SafeMath.sol:98:21:
   |
98 |         uint256 c = a * b;
   |                     ^^^^^
Note: 
Note that some information is erased after the execution of loops.
You can re-introduce information using require().

Warning: BMC: Condition is always true.
   --> circles-contracts/contracts/Hub.sol:294:17:
    |
294 |         require(steps < type(uint64).max);
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^
Note: Callstack:

Warning: BMC: Overflow (resulting value larger than 2**256 - 1) might happen here.
  --> circles-contracts/contracts/SafeMath.sol:98:21:
   |
98 |         uint256 c = a * b;
   |                     ^^^^^
Note: 
Note that array aliasing is not supported, therefore all mapping information is erased after a mapping local variable/parameter is assigned.
You can re-introduce information using require().
Note that some information is erased after the execution of loops.
You can re-introduce information using require().
Note that external function calls are not inlined, even if the source code of the function is available. This is due to the possibility that the actual called contract has the same ABI but implements the function differently.

Warning: BMC: Overflow (resulting value larger than 2**256 - 1) might happen here.
  --> circles-contracts/contracts/SafeMath.sol:98:21:
   |
98 |         uint256 c = a * b;
   |                     ^^^^^
Note: 
Note that some information is erased after the execution of loops.
You can re-introduce information using require().

Warning: BMC: Overflow (resulting value larger than 2**256 - 1) might happen here.
  --> circles-contracts/contracts/Hub.sol:67:13:
   |
67 |             iter += 1;
   |             ^^^^^^^^^
Note: 
Note that some information is erased after the execution of loops.
You can re-introduce information using require().

Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
 --> circles-contracts/contracts/Hub.sol:8:1:
  |
8 | contract Hub {
  | ^ (Relevant source part starts here and spans across multiple lines).
  ```

**Comment by leonardoalt** [comment]
Lots of `might happen` there =/
Found a bug when running on `Address.sol`:
https://github.com/ethereum/solidity/issues/10619

**Comment by leonardoalt** [comment]
I think the results from `Hub.sol` are ok though.

**Comment by axic** [comment]
```
Warning: CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
   --> circles-contracts/contracts/Hub.sol:277:43:
    |
277 |         for (uint i = 0; i < seen.length; i++) {
    |                                           ^^^
```

`seen` here refers to `address[] public seen;` so while technically it could have `2**256-1` elements, it is not practically possible. We really need assertion annotations :)

**Comment by leonardoalt** [comment]
For `a.push()`, we already add that the resulting length is `< uint.max - 1`, so that you can always push again without overflowing, since that would also not be practically possible (push overflow would also require 2**256 -1 operations). I'd say that similarly, we can add `length < uint.max - 1` for any `.length` access, so that it wouldn't overflow here as well.

**Comment by leonardoalt** [comment]
Running current develop on `Hub.sol` gives a huge amount of `underflow/overflow/div by 0 might happen here`. It would be good to try to understand why that is.

**Comment by leonardoalt** [comment]
My guess is again `pow` and the other nonlinear stuff making termination analysis fail and therefore non of the other inductive stuff works.

**Comment by leonardoalt** [comment]
We should revisit this with the current SMTChecker and z3/eldarica.

**Comment by pgebal** [comment]
I've run solc commit b84af3f420b542a3cfbd05ab7e71c81dfc2a2064 
on circles-contracts https://github.com/pgebal/circles-contracts/tree/smt_checker_test.

**Comment by pgebal** [comment]
results of running CHC `solc --bin --model-checker-engine chc --model-checker-solvers z3 --model-checker-show-unproved --model-checker-show-unsupported Hub.sol`:

```
Warning: This is a pre-release compiler version, please do not use it in production.

Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> Token.sol:173:31:
    |
173 |     ) public onlyHub returns (bool) {
    |                               ^^^^

Warning: Inline assembly may cause SMTChecker to produce spurious warnings (false positives).
  --> Address.sol:33:9:
   |
33 |         assembly { codehash := extcodehash(account) }
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Inline assembly may cause SMTChecker to produce spurious warnings (false positives).
   --> Address.sol:132:17:
    |
132 |                 assembly {
    |                 ^ (Relevant source part starts here and spans across multiple lines).

Info: CHC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Info: CHC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Warning: CHC: Division by zero might happen here.
  --> SafeMath.sol:86:17:
   |
86 |         require(c / a == b, "SafeMath: multiplication overflow");
   |                 ^^^^^

Warning: CHC: Division by zero might happen here.
   --> SafeMath.sol:121:21:
    |
121 |         uint256 c = a / b;
    |                     ^^^^^

Info: CHC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Warning: Contract deployment is only supported in the trusted mode for external calls with the CHC engine.
   --> Hub.sol:113:23:
    |
113 |         Token token = new Token(msg.sender);
    |                       ^^^^^^^^^^^^^^^^^^^^^

Warning: CHC: Out of bounds access might happen here.
   --> Hub.sol:280:56:
    |
280 |             transferValidator memory curr = validation[seen[i]];
    |                                                        ^^^^^^^

Warning: CHC: Out of bounds access might happen here.
   --> Hub.sol:286:25:
    |
286 |                 require(seen[i] == msg.sender, "Path doesn't send from transaction sender");
    |                         ^^^^^^^

Warning: CHC: Out of bounds access might happen here.
   --> Hub.sol:287:23:
    |
287 |                 src = seen[i];
    |                       ^^^^^^^

Warning: CHC: Out of bounds access might happen here.
   --> Hub.sol:293:24:
    |
293 |                 dest = seen[i];
    |                        ^^^^^^^

Warning: CHC: Out of bounds access might happen here.
   --> Hub.sol:310:31:
    |
310 |             delete validation[seen[i-1]];
    |                               ^^^^^^^^^

Warning: CHC: Out of bounds access might happen here.
   --> Hub.sol:334:27:
    |
334 |             address src = srcs[i];
    |                           ^^^^^^^

Warning: CHC: Out of bounds access might happen here.
   --> Hub.sol:335:28:
    |
335 |             address dest = dests[i];
    |                            ^^^^^^^^

Warning: CHC: Out of bounds access might happen here.
   --> Hub.sol:336:29:
    |
336 |             address token = tokenOwners[i];
    |                             ^^^^^^^^^^^^^^

Warning: CHC: Out of bounds access might happen here.
   --> Hub.sol:337:27:
    |
337 |             uint256 wad = wads[i];
    |                           ^^^^^^^

Warning: CHC: Division by zero might happen here.
   --> SafeMath.sol:157:16:
    |
157 |         return a % b;
    |                ^^^^^

Info: CHC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Warning: Contract code size is 29909 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
 --> Hub.sol:7:1:
```

What draws my attention are warnings on out of bounds access when the loop is:
`for (uint i = 0; i < seen.length; i++)` and  `i` is used as access index. I think Leo is right on this problem: https://github.com/ethereum/solidity/issues/10062#issuecomment-745551790

**Comment by pgebal** [comment]
results of running BMC with default `--model-checker-bmc-loop-iterations` setting: `solc --bin --model-checker-engine bmc --model-checker-solvers z3 --model-checker-show-unproved --model-checker-show-unsupported Hub.sol`

```
Warning: This is a pre-release compiler version, please do not use it in production.

Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> Token.sol:173:31:
    |
173 |     ) public onlyHub returns (bool) {
    |                               ^^^^

Warning: Inline assembly may cause SMTChecker to produce spurious warnings (false positives).
  --> Address.sol:33:9:
   |
33 |         assembly { codehash := extcodehash(account) }
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Inline assembly may cause SMTChecker to produce spurious warnings (false positives).
   --> Address.sol:132:17:
    |
132 |                 assembly {
    |                 ^ (Relevant source part starts here and spans across multiple lines).

Warning: BMC: Condition is always true.
  --> SafeMath.sol:31:17:
   |
31 |         require(c >= a, "SafeMath: addition overflow");
   |                 ^^^^^^
Note: Callstack:

Warning: BMC: Condition is always true.
  --> SafeMath.sol:86:17:
   |
86 |         require(c / a == b, "SafeMath: multiplication overflow");
   |                 ^^^^^^^^^^
Note: Callstack:

Info: BMC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Info: BMC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Info: BMC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Info: BMC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Warning: Contract deployment is only supported in the trusted mode for external calls with the CHC engine.
   --> Hub.sol:113:23:
    |
113 |         Token token = new Token(msg.sender);
    |                       ^^^^^^^^^^^^^^^^^^^^^

Warning: BMC: Condition is always false.
   --> Hub.sol:297:17:
    |
297 |         require(src != address(0), "Transaction must have a src");
    |                 ^^^^^^^^^^^^^^^^^
Note: Callstack:

Warning: BMC: Condition unreachable.
   --> Hub.sol:298:17:
    |
298 |         require(dest != address(0), "Transaction must have a dest");
    |                 ^^^^^^^^^^^^^^^^^^
Note: Callstack:

Warning: BMC: Condition unreachable.
   --> Hub.sol:301:17:
    |
301 |         require(validation[src].received == 0, "Sender is receiving");
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: Callstack:

Warning: BMC: Condition unreachable.
   --> Hub.sol:302:17:
    |
302 |         require(validation[dest].sent == 0, "Recipient is sending");
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: Callstack:

Warning: BMC: Condition unreachable.
   --> Hub.sol:304:17:
    |
304 |         require(validation[src].sent == validation[dest].received, "Unequal sent and received amounts");
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: Callstack:

Warning: BMC: Condition unreachable.
   --> Hub.sol:306:17:
    |
306 |         require(seen.length <= steps + 1, "Seen too many addresses");
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^
Note: Callstack:

Warning: BMC: Condition unreachable.
   --> Hub.sol:314:17:
    |
314 |         require(seen.length == 0, "Seen should be empty");
    |                 ^^^^^^^^^^^^^^^^
Note: Callstack:

Info: BMC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Warning: Contract code size is 29909 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
```

I am not sure why `Condition is always false` warning is printed. Context where it's printed is:
```
        address src;
        address dest;
        // iterate through the array of all the addresses that were part of the transaction data
        for (uint i = 0; i < seen.length; i++) {
            transferValidator memory curr = validation[seen[i]];
            // if the address sent more than they received, they are the sender
            if (curr.sent > curr.received) {
                // if we've already found a sender, transaction is invalid
                require(src == address(0), "Path sends from more than one src");
                // the real token sender must also be the transaction sender
                require(seen[i] == msg.sender, "Path doesn't send from transaction sender");
                src = seen[i];
            }
            // if the address received more than they sent, they are the recipient
            if (curr.received > curr.sent) {
                // if we've already found a recipient, transaction is invalid
                require(dest == address(0), "Path sends to more than one dest");
                dest = seen[i];
            }
        }
        // a valid path has both a sender and a recipient
        require(src != address(0), "Transaction must have a src");
```
We have a loop followed by a require statement on a variable `src` which is assigned inside the loop.
With the default loop iterations settings the loop is visited once and I think we shouldn't see this warning.
I'll add a test to our checker to figure out why that happens. @leonardoalt

**Comment by pgebal** [comment]
Finally BMC run with loop iterations set to 3 `solc --bin --model-checker-engine bmc --model-checker-solvers z3 --model-checker-show-unproved --model-checker-show-unsupported --model-checker-bmc-loop-iterations 3 Hub.sol`

```
Warning: This is a pre-release compiler version, please do not use it in production.

Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> Token.sol:173:31:
    |
173 |     ) public onlyHub returns (bool) {
    |                               ^^^^

Warning: Inline assembly may cause SMTChecker to produce spurious warnings (false positives).
  --> Address.sol:33:9:
   |
33 |         assembly { codehash := extcodehash(account) }
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Inline assembly may cause SMTChecker to produce spurious warnings (false positives).
   --> Address.sol:132:17:
    |
132 |                 assembly {
    |                 ^ (Relevant source part starts here and spans across multiple lines).

Warning: BMC: Condition is always true.
  --> SafeMath.sol:31:17:
   |
31 |         require(c >= a, "SafeMath: addition overflow");
   |                 ^^^^^^
Note: Callstack:

Warning: BMC: Condition is always true.
  --> SafeMath.sol:86:17:
   |
86 |         require(c / a == b, "SafeMath: multiplication overflow");
   |                 ^^^^^^^^^^
Note: Callstack:

Info: BMC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Info: BMC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Info: BMC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Info: BMC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Warning: Contract deployment is only supported in the trusted mode for external calls with the CHC engine.
   --> Hub.sol:113:23:
    |
113 |         Token token = new Token(msg.sender);
    |                       ^^^^^^^^^^^^^^^^^^^^^

Warning: BMC: Condition is always true.
   --> Hub.sol:314:17:
    |
314 |         require(seen.length == 0, "Seen should be empty");
    |                 ^^^^^^^^^^^^^^^^
Note: Callstack:

Info: BMC: 3 verification condition(s) proved safe! Enable the model checker option "show proved safe" to see all of them.

Warning: Contract code size is 29909 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
```

**Comment by pgebal** [comment]
After solving this issue: https://github.com/ethereum/solidity/issues/14449 the output for `Hub.sol`, when checked with the default `--model-checker-bmc-loop-iterations` setting has changed and now the following warning is reported:
```
Warning: BMC: Condition is always false.
   --> Hub.sol:298:17:
    |
298 |         require(dest != address(0), "Transaction must have a dest");
```
which I think is fine given that the loop in `Hub.sol` is:
```
address src;
address dest;
for (uint i = 0; i < seen.length; i++) {
            transferValidator memory curr = validation[seen[i]];
            // if the address sent more than they received, they are the sender
            if (curr.sent > curr.received) {
                // if we've already found a sender, transaction is invalid
                require(src == address(0), "Path sends from more than one src");
                // the real token sender must also be the transaction sender
                require(seen[i] == msg.sender, "Path doesn't send from transaction sender");
                src = seen[i];
            }
            // if the address received more than they sent, they are the recipient
            if (curr.received > curr.sent) {
                // if we've already found a recipient, transaction is invalid
                require(dest == address(0), "Path sends to more than one dest");
                dest = seen[i];
            }
        }
```
basically if for 1 loop iteration `src` is non-zero address, `dest` is a zero address
