### ISSUE TITLE
[SMTChecker] Features that could be more precise

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#10099]
This issue tracks features that are currently implemented in the SMTChecker in some form, but could be more precise:

- [x] erase knowledge only about assigned index https://github.com/ethereum/solidity/issues/6178
- [ ] variables of FunctionType https://github.com/ethereum/solidity/issues/8330
- [ ] memory/storage pointers https://github.com/ethereum/solidity/issues/9148
- [ ] some inline assembly https://github.com/ethereum/solidity/issues/10596
