### ISSUE TITLE
IR-based CompilerStack 

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10152]
The following features are missing in order to have feature parity:
- [x] Add CBOR metadata to the bytecode (requires #10179)
- [x] Support object (#10147)
- [x] Support runtimeObject -- needs an improvement in AssemblyStack (see https://github.com/ethereum/solidity/pull/10147#discussion_r514193653)
- [x] Add EIP-170 size check for runtimeObject (this could be moved to a generic location and not duplicated)
- [x] Support assemblyItems / runtimeAssemblyitems -- needs a change to MachineAssemblyObject (#10866)
- [ ] Support generatedSources
- [x] Support assemblyString -- needs some refactoring or exposing MachineAssemblyObject (#10866)
- [x] Support assemblyStringJSON -- needs major changes to libyul (exposing this EVM-specific field in MachineAssemblyObject) (#10866)
- [ ] Support functionEntryPoints -- depends on assemblyItems
- [x] Support gasEstimates -- depends on assemblyItems (#10866)
- [x] Support sourceMapping / runtimeSourceMapping -- depends on assemblyItems or expose MachineAssemblyObject (#10866 -- but this will be useful after #11086)
- [x] Keep source locations passed down to assembly (#11086)

**Comment by cameel** [comment]
I'm going to help with implementing the remaining stuff. @axic said the issue is actually 90% finished and he has a pending PR to push. So I'll wait for that and see what's left then.

Some comments from gitter about the remaining stuff, for later reference:

@axic
> @cameel: the metadata part depends on #10179, functionEntryPoints/gasEstimates depends exposing internal function pointers (which I guess we can just ignore), and generatedSources is just not supported yet in general

@cameel
> So, actually is there anything still left to do in #10152? :)

@axic
> Well, passing source locations through the IR. We had an old PR to support special comments in yul for source location annotations. I'll look it up and put it in an issue. But this is not strictly related to #10152, but more to feature completeness.
>
> However, what about `generatedSources` in the case of the IR?

@chriseth
> (...)
> ah actually maybe we do need it
> because the sources of internal routines should point to the generated sources instead
> so the whole IR should be a single 'generated source'
> and if we have a "high level source location" for a line of Yul, then its source location is that, otherwise it's the location in the IR file and the IR file is the generated source

**Comment by chriseth** [comment]
I might have changed my mind. Instead of `generated sources`, we could use the (already existing) `ir` field. Then each bytecode in the output has to source refereces: One "low-level source reference" referencing the (non-optimized) ir and optionally a "high-level source reference" referencing the solidity source code it was generated from.

**Comment by chriseth** [comment]
I would keep `generatedSources` empty for now. The IR is not really a "generated source".

As far as the function debug data is concerned, I'm working on that now.

**Comment by cameel** [comment]
I guess #11494 should be listed as a dependency for all the remaining bullet points here?
