### ISSUE TITLE
[SMTChecker] Verification progress tracker

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10163]
These are the contracts we have looked at. This is a list of feature support:

- [x] Myhtril/Slither examples (#6721)
- [ ] Solc-Verify examples (#8145)
- [x] Eth2.0 deposit contract (#9806)
- [ ] Circles UBI (#10062)
- [ ] UniswapV2 -- safemath...
- [ ] Gnosis Safe
- [ ] Gnosis MultiSigWallet https://github.com/ethereum/solidity/issues/11275
- [ ] Chai https://github.com/ethereum/solidity/issues/11276
- [ ] SafeMath (zeppelin) -- fails to handle
- [ ] chi gastoken

**Comment by leonardoalt** [comment]
We should make another list like this and go through contracts again.

**Comment by cameel** [comment]
How about going through current external tests? Maybe then we could also make it an automated test to detect regressions?
