### ISSUE TITLE
IR progress tracker (example contracts)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10390]
Here are a bunch of contracts we have been using:
- [x] Simple ERC20 token (#6478)
- [x] Eth2.0 deposit contract (#8853)
- [x] Gnosis MultiSigWallet (#9714)
- [x] Gnosis Safe (#9351)
- [ ] Uniswap V2 ("stacktoodeep")
- [x] snarks.sol (from tests)
- [x] chi
- [x] chai (https://github.com/axic/chai/tree/soldev)
- [x] Circles UBI (on `Token.sol`, `Hub.sol` fails) (#10115)

**Comment by axic** [comment]
CirclesUBI Hub.sol fails with (apparently this issue: #10115):
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp(2162): Throw in function std::__1::string solidity::frontend::YulUtilFunctions::readFromStorageDynamic(const solidity::frontend::Type &, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

**Comment by axic** [comment]
Obtained via changing #10235 (removing the `catch UnimplementedError`):

~~Issue A1: (must be #10115 I think) #10552~~ DONE
```
semanticTests/smoke/fallback.sol:
semanticTests/fallback/fallback_argument_to_storage.sol:
semanticTests/getters/string_and_bytes.sol:
semanticTests/constructor/bytes_in_constructors_unpacker.sol:
semanticTests/array/indexAccess/inline_array_index_access_strings.sol:
Exception during test: /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp(2164): Throw in function std::__1::string solidity::frontend::YulUtilFunctions::readFromStorageDynamic(const solidity::frontend::Type &, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

~~Issue A2: (Implemented in #10552)~~ DONE
```
semanticTests/array/string_allocation_bug.sol:
semanticTests/array/strings_in_struct.sol:
semanticTests/various/skip_dynamic_types_for_structs.sol:
semanticTests/variables/public_state_overridding_mapping_to_dynamic_struct.sol:
semanticTests/variables/public_state_overridding_dynamic_struct.sol:
semanticTests/getters/struct_with_bytes.sol:
semanticTests/getters/struct_with_bytes_simple.sol:
semanticTests/structs/conversion/recursive_storage_memory.sol:
semanticTests/structs/conversion/recursive_storage_memory_complex.sol:
Exception during test: /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp(2208): Throw in function std::__1::string solidity::frontend::YulUtilFunctions::readFromStorageReferenceType(const solidity::frontend::Type &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

~~Issue A3 (missing support for `type(C).name`): (#10579)~~ DONE
```
semanticTests/metaTypes/name_other_contract.sol:
Exception during test: /Users/alex/Projects/solidity/test/libsolidity/SolidityExecutionFramework.cpp(62): Throw in function solidity::bytes solidity::frontend::test::SolidityExecutionFramework::multiSourceCompileContract(const map<std::__1::string, std::__1::string> &, const std::__1::string &, const map<std::__1::string, solidity::test::Address> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::Error>
std::exception::what: Unimplemented feature error in /Users/alex/Projects/solidity/libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1745
[solidity::util::tag_comment*] = Unimplemented feature error in /Users/alex/Projects/solidity/libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1745
[solidity::langutil::tag_sourceLocation*] = [493,505]
```

~~Issue A4: (Implemented in #10577)~~ DONE
```
semanticTests/storage/mappings_array2d_pop_delete.sol:
semanticTests/storage/mappings_array_pop_delete.sol:
semanticTests/structs/delete_struct.sol:
Exception during test: /Users/alex/Projects/solidity/test/libsolidity/SolidityExecutionFramework.cpp(62): Throw in function solidity::bytes solidity::frontend::test::SolidityExecutionFramework::multiSourceCompileContract(const map<std::__1::string, std::__1::string> &, const std::__1::string &, const map<std::__1::string, solidity::test::Address> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::Error>
std::exception::what: Unimplemented feature error: setToZero for type t_mapping$_t_uint256_$_t_uint256_$ not yet implemented! in /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp:3570
[solidity::util::tag_comment*] = Unimplemented feature error: setToZero for type t_mapping$_t_uint256_$_t_uint256_$ not yet implemented! in /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp:3570
[solidity::langutil::tag_sourceLocation*] = [544,551]
```

~~Issue A5 (missing support for BitNot on FixedBytes)~~: (@axic) DONE
```
semanticTests/various/iszero_bnot_correct.sol:
Exception during test: /Users/alex/Projects/solidity/test/libsolidity/SolidityExecutionFramework.cpp(62): Throw in function solidity::bytes solidity::frontend::test::SolidityExecutionFramework::multiSourceCompileContract(const map<std::__1::string, std::__1::string> &, const std::__1::string &, const map<std::__1::string, solidity::test::Address> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::Error>
std::exception::what: Unimplemented feature error: Unary operator not yet implemented in /Users/alex/Projects/solidity/libsolidity/codegen/ir/IRGeneratorForStatements.cpp:706
[solidity::util::tag_comment*] = Unimplemented feature error: Unary operator not yet implemented in /Users/alex/Projects/solidity/libsolidity/codegen/ir/IRGeneratorForStatements.cpp:706
[solidity::langutil::tag_sourceLocation*] = [324,344]
```

~~Issue A6: (is part of #10552)~~ DONE
```
semanticTests/structs/memory_structs_read_write.sol:
semanticTests/structs/memory_structs_nested_load.sol:
semanticTests/array/copying/storage_memory_nested_struct.sol:
Exception during test: /Users/alex/Projects/solidity/test/libsolidity/SolidityExecutionFramework.cpp(62): Throw in function solidity::bytes solidity::frontend::test::SolidityExecutionFramework::multiSourceCompileContract(const map<std::__1::string, std::__1::string> &, const std::__1::string &, const map<std::__1::string, solidity::test::Address> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::Error>
std::exception::what: Unimplemented feature error in /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp:2208
[solidity::util::tag_comment*] = Unimplemented feature error in /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp:2208
[solidity::langutil::tag_sourceLocation*] = [643,663]
```

~~Issue A7: (Implemented in #10554)~~ DONE
```
semanticTests/array/push/push_no_args_bytes.sol:
semanticTests/array/copying/empty_bytes_copy.sol:
Exception during test: /Users/alex/Projects/solidity/test/libsolidity/SolidityExecutionFramework.cpp(62): Throw in function solidity::bytes solidity::frontend::test::SolidityExecutionFramework::multiSourceCompileContract(const map<std::__1::string, std::__1::string> &, const std::__1::string &, const map<std::__1::string, solidity::test::Address> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::Error>
std::exception::what: Unimplemented feature error: Byte Arrays not yet implemented! in /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp:1340
[solidity::util::tag_comment*] = Unimplemented feature error: Byte Arrays not yet implemented! in /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp:1340
[solidity::langutil::tag_sourceLocation*] = [196,208]
```

~~Issue A8: (Implemented in #10560)~~ DONE
```
semanticTests/array/push/array_push_struct.sol:
Exception during test: /Users/alex/Projects/solidity/test/libsolidity/SolidityExecutionFramework.cpp(62): Throw in function solidity::bytes solidity::frontend::test::SolidityExecutionFramework::multiSourceCompileContract(const map<std::__1::string, std::__1::string> &, const std::__1::string &, const map<std::__1::string, solidity::test::Address> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::Error>
std::exception::what: Unimplemented feature error in /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp:2993
[solidity::util::tag_comment*] = Unimplemented feature error in /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp:2993
[solidity::langutil::tag_sourceLocation*] = [391,403]
```

**Comment by axic** [comment]
Did a second run where forcefully displaying failing semantic tests.

Issue B1: Tests implicitly assume ABI coder v1, while the IR forcefully uses to v2.

~~Issue B2: Exponent and certain other overflow cases are handled differently -- this will be a non issue after 0.8.0. See #10762, #10753.~~ DONE

~~Issue B3: Modifiers are pretty much not implemented -- see #10413.~~ DONE

~~Issue B4: `runtime/creationCode` is not padded: -- see #10774.~~ DONE
```
semanticTests/various/code_access_padding.sol: FAIL
  Contract:
    contract D {
        function f() public pure returns (uint256) {
            return 7;
        }
    }
    
    
    contract C {
        function diff() public pure returns (uint256 remainder) {
            bytes memory a = type(D).creationCode;
            bytes memory b = type(D).runtimeCode;
            assembly {
                remainder := mod(sub(b, a), 0x20)
            }
        }
    }
    

  Running via Yul:
  Expected result:
  // diff() -> 0 # This checks that the allocation function pads to multiples of 32 bytes #

  Obtained result:
  // diff() -> 0x17 # This checks that the allocation function pads to multiples of 32 bytes #
```

~~Issue B5: revert reasons are missing -- see #8252.~~ DONE

~~Issue B6: array copying failures -- see #10412.~~ DONE

**Comment by mijovic** [comment]
List of tests failing with different results viaYul
https://github.com/ethereum/solidity/pull/10546#issuecomment-749441119

**Comment by mijovic** [comment]
#10689 Last remaining test for array copying

**Comment by ekpyron** [comment]
- [x] SolidityEndToEndTest/shift_bytes_cleanup (https://github.com/ethereum/solidity/pull/10817)
- [x] SolidityEndToEndTest/bare_call_return_data (https://github.com/ethereum/solidity/pull/10815)
- [x] SolidityEndToEndTest/abi_encode_with_signature (#10776)
- [x] SolidityEndToEndTest/abi_encode_with_signaturev2 (#10776)
- [x] SolidityEndToEndTest/uninitialized_internal_storage_function (#10808)
- [x] SolidityEndToEndTest/strip_reason_strings (#10807)

seem to be failing tests in SolidityEndToEndTests.cpp via IR. Plus the following throw:

- [x] SolidityEndToEndTest/internal_constructor (https://github.com/ethereum/solidity/pull/10815)
- [x] SolidityEndToEndTest/copying_bytes_multiassign (#10804)
- [x] SolidityEndToEndTest/abi_encodePacked (https://github.com/ethereum/solidity/pull/10816 )


See https://github.com/ethereum/solidity/pull/10782
Probably some of them are in progress though, especially ``abi_encode_with_signature*`` in https://github.com/ethereum/solidity/pull/10776 - and others may be spurious, I didn't have a detailed look.

**Comment by axic** [comment]
In #10780 tried to forcefully enable all disabled tests, three could be enabled, and the rest are the following:
- semanticTests.calldata.calldata_array_dynamic_bytes: would be nice to check if the stack too deep error can be solved
- semanticTests.various.negative_stack_height: would be nice to check if the stack too deep error can be solved
- semanticTests.array.copying.dirty_memory_bytes_to_storage_copy: likely correctly disabled (mentioned in the ir breaking changes)
- semanticTests.revertStrings.function_entry_checks_v1: this is correctly disabled
- semanticTests.modifiers.function_modifier_loop: likely correctly disabled
- semanticTests.modifiers.function_modifier_multi_with_return: likely correctly disabled
- semanticTests.modifiers.function_modifier_multi_invocation: likely correctly disabled

As @ekpyron mentioned, probably we should leave a comment in the files explaining a reason they are disabled.

**Comment by chriseth** [comment]
I think some "debug revert strings" have not been implemented yet.

**Comment by chriseth** [comment]
Actually no, they are all there, the one I thought was missing is an ABIv1-only message.

**Comment by axic** [comment]
We could look at top gas consumer contracts, translate them to 0.8.x and check the gas usage of legacy vs. ir codegen.

A good way to find such contracts:  https://oko.palkeo.com/
