### ISSUE TITLE
NatSpec v2

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#11156]
Natspec JSON changes (non-breaking):
- [ ] #11114 (events and errors as arrays instead of hashmap)
- [ ] #11120 (change params/returns into an array instead of hashmap)
- [x] #11158 (include events/errors in the devdoc)
- [ ] include the `@notice` in the devdoc too

Natspec syntax changes (potentially breaking -- maybe has to wait for 0.9.0):
- [x] #10921 -- [explanation here](https://github.com/ethereum/solidity/issues/11156#issuecomment-810338240)
- [ ] disallow `@return` for events

**Comment by axic** [comment]
We may want to consider the following too:
- #3097 to also output internal functions in the devdocs, given that could change the format as well.
- #9553 and #10281 to clear up the behaviour of the notice and dev tags
- #11158 to include events/errors in the devdoc
- anything I missed from #1141

Lastly we may want to consider merging devdoc/userdoc into a single output.

**Comment by chriseth** [comment]
Do we also want to output free functions?

**Comment by axic** [comment]
I think so, under the "internal functions" umbrella.

**Comment by Marenz** [comment]
Should we maybe have an extra issue for turning `returns` into an array? Or do you expect it to be part of #10921?

**Comment by axic** [comment]
@Marenz #11120 should cover both.

**Comment by axic** [comment]
For #10921 we discussed to change how public struct state variables work:
- In the syntax for `@return` each of the member variables should be described.
- In the JSON the `returns` field should contain an array (the same structure as #11120).

**Comment by axic** [comment]
We also discussed:
- #3097 -- we definitely want to include non-public functions, but it seems to be quite a bit of design work left to be done
- #10281 -- we may want this, but need to agree on rules
