### ISSUE TITLE
Tracking unimplemented fixed point features

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#11719]
- [ ] `type(ufixedMxN).min` and `.max`
- [ ] Error when `ufixedMxN` where `N` is too large to fit into `M` (e.g., `ufixed8x80` is currently allowed.) Controversial: don't implement.
- [x] Check that comparing two rational numbers for equality does not apply rounding before comparison.
- [x] Check that the abi decoder reverts if the input value is out of range for the type (part of https://github.com/ethereum/solidity/pull/11704)
- [x] check that storing and loading from storage works properly (especially truncating sign bits)
- [x] check that getters work properly
- [x] check that rounding is towards zero for precision loss and conversion to integer (also for negative values)
- [x] comparison operators (codegen + tests)
- [x] abi json (fixed by https://github.com/ethereum/solidity/pull/11825 )

Also https://github.com/ethereum/solidity/issues/409 has some. A fresh issue to track things that come up in PRs.

**Comment by cameel** [comment]
I guess this is still relevant until we decide to officially deprecate fixed-point types.

**Comment by ekpyron** [comment]
This isn't relevant anymore. If we don't have it, we should instead have an issue for deprecating and removing the existing fixed-point types.
