### ISSUE TITLE
0.8.7 release checklist

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#11786]
### Requirements
 - [ ] Lauchpad (Ubuntu One) account
 - [ ] gnupg key (has to be version 1, gpg2 won't work) for `your-name@ethereum.org` created and uploaded
 - [x] Readthedocs account, access to the Solidity project
 - [ ] Write access to https://github.com/ethereum/homebrew-ethereum

### Documentation check
 - [X] Run `make linkcheck` from within `docs/` and fix any broken links it finds. Ignore false positives caused by `href` anchors and dummy links not meant to work.

### Blog Post
 - [X] Create a post on https://github.com/ethereum/solidity-blog and explain some of the new features or concepts.

### Changelog
 - [X] Sort the changelog entries alphabetically and correct any errors you notice.
 - [X] Create a commit on a new branch that updates the ``Changelog`` to include a release date.
 - [X] Run ``./scripts/tests.sh`` to update the bug list.
 - [X] Create a pull request and wait for the tests, merge it. (https://github.com/ethereum/solidity/pull/11784)

### Create the Release
 - [x] Create Github release page: https://github.com/ethereum/solidity/releases/new (https://github.com/ethereum/solidity/releases/tag/untagged-bb8472b69f96d0c0f2d8)
 - [x] On the release page, select the ``develop`` branch as new target and set tag to the new version (e.g. `v0.8.5`) (make sure you only `SAVE DRAFT` instead of `PUBLISH RELEASE` before the actual release)
 - [x] Thank voluntary contributors in the Github release page (use ``git shortlog -s -n -e v0.5.3..origin/develop``).
 - [x] Check that all tests on the latest commit in ``develop`` are green.
 - [x] Click the `PUBLISH RELEASE` button on the release page, creating the tag.
 - [x] Wait for the CI runs on the tag itself.

### Download Binaries
 - [x] Take the ``solc.exe`` binary from the ``b_win_release`` run of the released commit in circle-ci and add it to the release page as ``solc-windows.exe``.
 - [x] Take the ``solc`` binary from the ``b_osx`` run of the released commit in circle-ci and add it to the release page as ``solc-macos``.
 - [x] Take the ``solc`` binary from the ``b_ubu_static`` run of the released commit in circle-ci and add it to the release page as ``solc-static-linux``.
 - [x] Take the ``soljson.js`` binary from the ``b_ems`` run of the released commit in circle-ci and add it to the release page as ``soljson.js``.

### Update [solc-bin](https://github.com/ethereum/solc-bin/)
 - [x] Copy files to solc-bin:
     ```bash
     VERSION=0.8.4
     COMMIT="c7e474f2"
     SOLC_BIN="/home/me/solc-bin"
     chmod +x solc-static-linux solc-macos
     cp soljson.js $SOLC_BIN/bin/soljson-v$VERSION+commit.$COMMIT.js
     cp solc-static-linux $SOLC_BIN/linux-amd64/solc-linux-amd64-v$VERSION+commit.$COMMIT
     cp solc-macos $SOLC_BIN/macosx-amd64/solc-macosx-amd64-v$VERSION+commit.$COMMIT
     cp solc-windows.exe $SOLC_BIN/windows-amd64/solc-windows-amd64-v$VERSION+commit.$COMMIT.exe
 - [x] Run ``./update --reuse-hashes`` in ``solc-bin`` and verify that the script has updated ``list.js``, ``list.txt`` and ``list.json`` files correctly and that symlinks to the new release have been added in ``solc-bin/wasm/`` and ``solc-bin/emscripten-wasm32/``.
 - [x] Create a pull request and merge. (https://github.com/ethereum/solc-bin/pull/96)

### Homebrew and MacOS
 - [ ] Update the version and the hash (``sha256sum solidity_$VERSION.tar.gz``) in https://github.com/Homebrew/homebrew-core/blob/master/Formula/solidity.rb (https://github.com/Homebrew/homebrew-core/pull/83103)
 - [x] Update the version and the hash (``sha256sum solidity_$VERSION.tar.gz``) in https://github.com/ethereum/homebrew-ethereum/blob/master/solidity.rb (https://github.com/ethereum/homebrew-ethereum/pull/297)

### Docker (@ekpyron)
 - [x] Run ``./scripts/docker_deploy_manual.sh v$VERSION``).

### PPA (@ekpyron)
 - [x] Change ``scripts/release_ppa.sh`` to match your key's email and key id.
 - [x] Run ``scripts/release_ppa.sh v$VERSION`` to create the PPA release (you need the relevant openssl key).
 - [x] Wait for the ``~ethereum/ubuntu/ethereum-static`` PPA build to be finished and published for *all platforms*. SERIOUSLY: DO NOT PROCEED EARLIER!!! *After* the static builds are *published*, copy the static package to the ``~ethereum/ubuntu/ethereum`` PPA for the destination series ``Trusty``, ``Xenial`` and ``Bionic`` while selecting ``Copy existing binaries``.

### Documentation (@franzihei)
 - [x] Build the new version on https://readthedocs.org/projects/solidity/ (select `latest` at the bottom of the page and click `BUILD`).
 - [x] In the admin panel, select `Versions` in the menu and set the default version to the released one.

### Release solc-js (@hrkrshnn)
 - [x] Wait until solc-bin was properly deployed. You can test this via remix - a test run through remix is advisable anyway.
 - [x] Increment the version number, create a pull request for that, merge it after tests succeeded. (https://github.com/ethereum/solc-js/pull/539)
 - [x] Run ``npm publish`` in the updated ``solc-js`` repository.
 - [x] Create a tag using ``git tag --annotate v$VERSION`` and push it with ``git push --tags``.

### Post-release
 - [x] Publish the blog post. (https://blog.soliditylang.org/2021/08/11/solidity-0.8.7-release-announcement/)
 - [x] Create a commit to increase the version number on ``develop`` in ``CMakeLists.txt`` and add a new skeleton changelog entry.
 - [x] Announce on Twitter, including links to the release and the blog post.
 - [x] Share announcement on Reddit and Solidity forum.
 - [x] Update the release information section on [soliditylang.org](https://github.com/ethereum/solidity-portal).
 - [x] Lean back, wait for bug reports and repeat from step 1 :)

**Comment by franzihei** [comment]
Just did the last bits by announcing the release on Reddit and the forum. Here are the links:
- Twitter: https://twitter.com/solidity_lang/status/1425528300143796224
- Reddit: https://www.reddit.com/r/ethdev/comments/p2vei3/solidity_v087_is_out_adds_support_for_the_basefee/
- Forum: https://forum.soliditylang.org/t/solidity-v0-8-7-has-been-released-adds-support-for-the-basefee-opcode-and-more/453

I guess that concludes this release. Closing this issue, please re-open if you think something is still missing.
