### ISSUE TITLE
External test benchmarking extensions

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12522]
#12441 adds benchmarking functionality to our external tests. I have a lot of ideas for extra improvements and not all of them may be worth the effort so I'm creating this issue to discuss them.

Current ideas:
- [ ] **Compilation time benchmarking**. Including the compilation duration in the benchmark JSON.
- [ ] **Diff repo**. Currently you have to manually download and diff the results. We could instead have a repository where the `c_ext_benchmarks` job commits the JSON files. It would have branches corresponding to the main repo (including `develop`) and you could go there and easily view the diff with the base branch via Github UI.
- [x] **Script for calculating gas differences**. I chose the current JSON structure to be easily diffable but it might still not be as convenient as just seeing a straight difference between two gas values. We could have a script that takes two benchmarks and produces a JSON file with absolute and/or relative differences. (done in #12804)
    - [x] Could also support producing a Markdown table. Might be easier to view and could be posted in a github comment. (done in #12804)
- [x] **Benchmark diff for PRs**. We could have a job that finds artifacts from a CI run on the base branch, calculates the diff with the current PR, creates a markdown table and posts it in the PR. (done in #12818, but without posting a comment in the PR)
    - Might be too spammy unless we can do it in such a way that it's a single comment that gets automatically updated (like it works with coverage for example).
- [ ] **Dumping Standard JSON from external tests**. External tests are pretty heavy. To make reproducing problems locally easier, we could have the test extract the combined Standard JSON input that the framework uses for compilation and attach it as an artifact.
- [ ] **Dumping Yul from external tests**. The external tests can relatively easily extract the `--ir-optimized` output that might be useful to inspect the effect of our optimizer changes in more detail. It could be zipped into a single package and attached as an artifact.
    - [ ] We could also store it in the diff repo.
- [ ] **Weekly benchmark summary**. A weekly job that runs `c_ext_benchmarks`, creates a short table from the summary JSON and posts it on gitter. For brevity the table would only list the output from one preset (the one with max optimization), not all 6.
- [ ] **Weekly benchmark diff**. The weekly summary job could use the CircleCI API to get a compiler binary from last week, get two benchmark outputs and post just the differences instead of absolute values.

**Comment by cameel** [comment]
Just added a new idea. We could have a job that posts a table with gas cost diff compared to base branch (or always `develop`) in each PR. Not sure if it wouldn't be too annoying though.

**Comment by ekpyron** [comment]
It being nicely readable output in a CI run or a CI artifact or so would probably be enough and less annoying...
As you wrote: If the logic was clever enough not to re-post on new pushs, but to edit its initial comment, it might be fine, but maybe also more trouble than it's worth :-).

**Comment by cameel** [comment]
I'm going to mark this issue as "medium impact" for "Dumping Standard JSON from external tests". Maybe I should put it in a separate issue. Being able to easily take the framework out of the equation and reproduce ext test compilation with only the compiler would be very helpful for profiling IR - which is very important and should be made easier.
