### ISSUE TITLE
[Docs] Order of contract parts / Solidity Style Guide maintenance

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#12614]
## Page

https://docs.soliditylang.org/en/latest/style-guide.html?highlight=style%20guide

## Abstract

It is specified:

> Inside each contract, library or interface, use the following order:

But this advice is not followed in examples.

<img width="537" alt="Screen Shot 2022-02-01 at 19 14 07" src="https://user-images.githubusercontent.com/382183/152072835-4a95955e-7a29-40f6-a60b-143660c3f69b.png">
<img width="446" alt="Screen Shot 2022-02-01 at 19 14 25" src="https://user-images.githubusercontent.com/382183/152072837-f652e4f9-647d-4582-a139-a9da150491db.png">

THE QUESTION:

> Should constructor be specified to be above modifiers?
> Or should constructor be moved down with the functions in that example?

## Pull request

(I can provide after answering THE QUESTION)

**Comment by ekpyron** [comment]
Right, thanks, I had not paid attention to constructors when merging https://github.com/ethereum/solidity/pull/12569...
Looking at the examples, I also realize that we don't specify a place for ``error`` declarations - and whatever we'd specify, the ``safe-remote.rst`` example would violate it :-)... and it already violates the event-modifier ordering... and it has the constructor *after* the modifiers... hm...

Also the part about "contract elements" should probably be renamed to "file-level elements" these days and would need to account for the new file-level elements like free functions and file-level error declarations...

Since the "Order of Functions" section considers the constructor a function, it would be "easier" to just move the constructor down in the examples... however, visually I personally find it more appealing to have it before :-)... EDIT: then again you can apply modifiers to constructors...

I'll ping our channel for more opinions!

**Comment by ekpyron** [comment]
We briefly discussed this in our meeting today and we would actually ideally like to hand over the maintenance of the style guide to the community, since we don't want to impose any personal preferences and would rather like the guide to reflect common practice in the community.
Any suggestions on how best to organize that?

**Comment by fulldecent** [comment]
Thank you for reviewing. Yes, that sounds good since it does not have any normative impact on Solidity proper.

Here is a recommend plan. And I volunteer to take all the responsibility and the work for these.

# Work plan

- [ ] Create new style repo https://github.com/ethereum/solidity-style-guide just for the style guide

  - [ ] Name "Solidity Community Style Guide"
  - [ ] Add me as maintainer

  - [ ] I'll publish it as Markdown + GitHub Pages to https://ethereum.github.io/solidity-style, super simple

  - [ ] I'll make up a project scope and guide the project towards all its goals
    - [ ] Updating documentation
    - [ ] Maintaining compatible settings for editorconfig, solhint, etc.
    - [ ] Goal is to make a reasonable, community-supported style guide to enhance readability of Solidity code across projects and to explain clearly why each rule promotes readability

- [ ] Find any relevant issues in this repo and note/transfer/copy there

- [ ] Look at the blame file and invite relevant people over to the new project
- [ ] Decouple style guide from Solidity repo, link to the new repo as a "recommendation", not as a "requirement":
  - [ ] Update https://github.com/ethereum/solidity/blob/f386ed28a0696083da9a8ce76bb6cfe6f62ea1ce/docs/style-guide.rst
    - [ ] Link to the new page (because there are many back links to this page)
  - [ ] Update https://github.com/ethereum/solidity/blob/de7b5a94ec8407bc1db3df7f1e041123d94b501e/docs/index.rst
  - [ ] Update https://github.com/ethereum/solidity/blob/563357cfecfa0d232d2fb5721420d7f16cb36105/docs/contributing.rst
- [ ] Reach out to request updates for backlinks to old page (attached)

# Required resources to start

- [ ] Create the repo above
  - [ ] Add me as a contributor
  - [ ] Add me as an admin, or instead help me just to turn off Discussions, Wiki, Projects, and turn on GitHub pages with https required
  - [ ] Grant my project charter (i.e. scope) above for the authority I need to execute those duties
- [ ] If it is not an option to create that repo or to add me, then I could create at fulldecent/solidity-style-guide (probably not worthwhile to make a new organization just for this small project)
- [ ] Tacit understanding that if the style guide project is run well, then PRs will continue to be accepted in the Solidity repo which update code listings to match that style

---

[baccklinks.csv.zip](https://github.com/ethereum/solidity/files/7990723/baccklinks.csv.zip)

**Comment by ekpyron** [comment]
That sounds great, thank you very much for volunteering for this!
We'll discuss this internally and will get back to you - and maybe it actually makes sense to have a call about this? For example, you're welcome to join our [design call next Wednesday](https://docs.soliditylang.org/en/latest/contributing.html#team-calls) or we could try and schedule a dedicated call about this, if you like.

**Comment by fulldecent** [comment]
Thank you, I'm in. Will catch you there.

**Comment by cameel** [comment]
Decision from the call: we're fine handing over maintenance of the style guide to @fulldecent but we prefer the guide to stay in the main repo / main docs. At least unless it turns out it's not working out well for some reason. We're on board with the rest of the roadmap.

We're going to add @fulldecent to [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) to give him direct access to the guide. This needs to be done by someone with owner or admin access to the repo (@chriseth, @axic).

BTW, since the discussion about maintenance basically took over this issue, I'm adjusting the title to reflect that.

**Comment by chriseth** [comment]
Added codeowners file, but I think this only enables review auto-requests and nothing else: https://github.com/ethereum/solidity/pull/12692

**Comment by Marenz** [comment]
Out of curiousity: Any update on this?

**Comment by NunoFilipeSantos** [comment]
Hi @fulldecent ! Would you be able to provide an update?

**Comment by fulldecent** [comment]
In this file I found that `error` is coming after `event`. This seems like a very reasonable choice—errors and events are both primarily useful off-chain, and if we're being positive `event`s which are good should be considered before `error`s which are bad.

OpenZeppelin Contracts is not using `error` yet.

---

Thank you, PR sent in https://github.com/ethereum/solidity/pull/13679

---

As for discussing file-level stuff outside of a contract declaration, let's use a different issue for that. I have not seen well known projects using this in the wild yet.
