### ISSUE TITLE
User Defined value types and operators for them using "using for"

### ISSUE THREAD

**Issue by nishant-sachdeva** [ethereum/solidity#13316]
- [x] https://github.com/ethereum/solidity/issues/9211
- [x] https://github.com/ethereum/solidity/issues/11531
- [x] https://github.com/ethereum/solidity/issues/11969

**Comment by cameel** [comment]
This issue was replaced by #13718.
