### ISSUE TITLE
Immutable Reference Types

### ISSUE THREAD

**Issue by nishant-sachdeva** [ethereum/solidity#13323]
WHAT
WHY
HOW
Broader discussion in #12587

Concrete steps:
- [ ] https://github.com/ethereum/solidity/issues/13368
- [ ] https://github.com/ethereum/solidity/issues/13369
- [ ] Define further issues for implementing code generation.

**Comment by cameel** [comment]
@ekpyron Do we consider something like #13448 as a part of this?

**Comment by ekpyron** [comment]
> @ekpyron Do we consider something like #13448 as a part of this?

What that one suggests, is pretty much what we we *did* decide to do for this and which is what https://github.com/ethereum/solidity/issues/13368 and https://github.com/ethereum/solidity/issues/13369 are about.

**Comment by cameel** [comment]
I'm closing this since we have too many redundant issues about reference type immutables. #13723 is the same thing.

Both are also really redundant with #12587.
