### ISSUE TITLE
Solidity implementation of EOF specification

### ISSUE THREAD

**Issue by NunoFilipeSantos** [ethereum/solidity#13717]
### What

Work towards Solidity generating EOF bytecode.

### Why

Harness the benefits that triggered EOF as evolution path in the EVM.

#### 2022 Q4 Step 1: Work together with Ipsilon to iron out the remaining details in the EOF specification;
  - [x] Jump-table static jumps (RJUMPV)
  - [x] Bytecode deduplication across functions on libevmasm level. (variants of TAILCALLF?)
  - [x] Try to include immediate swaps and dups into EOF to make avoiding stack-too-deep errors easier.

#### 2022 Q4 Step 2: Implement an experimental version of EOF to support EOFs inclusion in a hard-fork
   - [x]  This will involve disabling and refactoring parts of the libevmasm optimizer.

### Out of scope
For now:
#### Step 3: Follow and participate on the discussion to expand EOF,
  - [ ] implement it
  - [ ] release it.
  - [ ] Cleanup [this PR](https://github.com/ethereum/solidity/pull/13825)

- Implement EOF code generation in legacy non-via-IR codegen.
- Reproduce equal code deduplication to non-EOF paths at all cost.

---
### Resources

1. [Matrix room](https://matrix.to/#/!xKcViOTsACMyxYoGLy:matrix.org?via=matrix.org&via=ekpyron.org)
2. Notes on the discussion of EOF itself: https://notes.ethereum.org/0odM_jbbRTC7uPJtvHBPKg#Nov-21st
3. Notes on organization of Implementation: https://notes.ethereum.org/K9Pzvi_TSJqNEUzTzmnf-g
