### ISSUE TITLE
Shanghai Support

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#14073]
### Tasks
- [x] Add EVM version Shanghai.
- [ ] Implement [EIP-3855: PUSH0 instruction](https://eips.ethereum.org/EIPS/eip-3855)
   - [x] Add support for the opcode in libevmasm.
   - [x] Change generation of bytecode for pushes with zero-value in Assembly::assemble.
   - [x] #14225
   - [ ] Adjust constant optimizer to take PUSH0 into account. (can be done in a later step after 0.8.20, if need be) (https://github.com/ethereum/solidity/pull/14117)
   - [x] Use PUSH0 to replace codegen for "Junk" stack slots in the optimized evm code transform. (https://github.com/ethereum/solidity/pull/14133)
- [x] Take [EIP-3860: Limit and meter initcode](https://eips.ethereum.org/EIPS/eip-3860) into account. (https://github.com/ethereum/solidity/pull/14127)
- [x] Make `Shanghai` as the default EVMVersion (https://github.com/ethereum/solidity/pull/14158)
- [x] Testing: `evmHost.cpp` should populate the access list of `coinbase`. (Minor)
- [ ] Testing: `evmhost` change latest revision to Shanghai. (Minor)
- [x] Update Docs

---
### References
- [Shanghai Network Upgrade Specification](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md)
- Upgrade schedule: Mainnet - 4/12/2023, 10:27:35 PM (UTC)

**Comment by ekpyron** [comment]
> Adjust Yul optimizer to never CSE zeroes.

For the record: this part we can do in a subsequent step - as a matter of fact, as a first step plain support for the Opcode and generating it on a push with zero value in Assembly::assemble is enough for a first PR - the optimizer tweaking we can do later in a secondary step.

**Comment by ekpyron** [comment]
Changing the milestone to 0.8.21 for the remaining minor improvements in the optimizer.

**Comment by hrkrshnn** [comment]
I also think we didn't implement this for `--opcodes` output yet. At least it doesn't seem to give me `PUSH0`. I'll check this.

**Comment by ekpyron** [comment]
> I also think we didn't implement this for `--opcodes` output yet. At least it doesn't seem to give me `PUSH0`. I'll check this.

Should work implicitly (but better to confirm to be sure)

**Comment by NunoFilipeSantos** [comment]
Shanghai support was released. The rest are optimizations we will eventually get to.
