### ISSUE TITLE
Type Inference/Checking for Experimental Solidity

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#14284]
### What
After introducing ``pragma experimental solidity;`` we want to introduce a basic mechanism for Hindley-Milner-style type inference on a suitably reduced subset of the language, extend that by type classes, and move most of the hardcoded via-IR code generation to the standard library.

### How
In experimental language mode, replace the current analysis after syntax checking with a new Hindley-Milner-style type inference system. This will involve building a new separate kind of AST annotation system as well. After the basic infrastructure is there, roughly follow these steps:
  - [x] Only non-function-value types only in free functions no type classes.
  - [x] Introduce type classes.
  - [ ] Move definitions for built-in types to the standard library; implement ABI en-/decoding in the standard library.
  - [ ] Sufficient code generation to allow compiling deployable contracts with functions acting on value types; first version without storage
  - [ ] Implement function types.
  - [ ] Implement loading from and writing to storage for value types using type classes.
  - [ ] Implement reference types (i.e. build the required type system mechanisms (even linear types?) to then actually implement them in the standard library).
  - [ ] Implement more types and language features.
  - [ ] Solve the inheritance issue.

### Milestones
- [ ] The first milestone is reached as soon as we have type inference for value types and type classes.
- [ ] The second milestone is reached once we have ABI encoding/decoding and the code generation skeleton reached.
- [ ] The third milestone is reached once we have reference types reintroduced via the standard library, and experimental solidity starts becoming real-world-usable.
- [ ] The fourth milestone is reached when the first more complex real-world contracts can be transitioned to experimental solidity.
- [ ] The final milestone is reached when experimental solidity is sufficiently expressive to cover most existing contracts

---
### Resources

1. [2023 Berlin Team Week Notes](https://notes.ethereum.org/-hRCMVLpRAiGEiMbhEVpzg#References)
2. [2023-07-02 Daniel's Hindley-Milner-Style Type Inference presentation](https://drive.google.com/file/d/1eiPjkmvOpfki1V99pEXKvUEqFIhe1RRU/view?usp=sharing)

**Comment by clonker** [comment]
Experimental solidity has been removed in the course of https://github.com/argotorg/solidity/issues/16124
