### ISSUE TITLE
0x109390594d0ef9B40B4B745Cac6ceCf37a179417

### ISSUE THREAD

**Issue by KARINACAREPOTO** [ethereum/solidity#15116]
## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/solidity/issues/14985
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/solidity/pull/15001
- [ ] https://github.com/ethereum/solidity/pull/15112
```

```[tasklist]
### Tasks
- [x] Add a draft title or issue reference here
- [ ] https://github.com/ethereum/solidity/pull/15001
```
