### ISSUE TITLE
SMT checker PoC1

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3257]
Things to be done before the SMT checker can be practically useful:

 - [x] integer, address and bool types #3712 
 - [x] fixed-sized arrays #3712 
 - [x] tuples #4141
 - [x] Member access of storage arrays and mappings #3651 
 - [x] basic `tx`, `msg` and `block` variables. #5192
 - [x] address members #5262
 - [x] modifiers #5193
 - [x] internal function calls #5189 
 - [x] external function calls #5190 #6400 
 - [x] non-fractional rational number types
 - [x] compound assignment operators #6006 
 - [x] unary increment/decrement #6401
 - [x] show unsupported warning message for assembly blocks #6418 
 - [x] mod #6443
 - [x] do not crash (or ICE) on complex examples #6009 #6699
