### ISSUE TITLE
Improve error messages for implicit type conversions

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#4128]
`binaryOperatorResult` and `isImplicitlyConvertible` currently only return few error messages.

The purpose of this issue is to collect cases that can be improved.

Two good starting points are: https://ethereum.stackexchange.com/search?q=not+compatible and https://ethereum.stackexchange.com/search?q=not+convertible

---------
Work done so far:

`binaryOperatorResult`

 * [x] For AddressType: "Arithmetic operations on addresses are not supported. Convert to integer first before using them." (#3879)
* [x] For IntegerType: "Exponentiation is not allowed for signed integer types." (#3879)
* [x] For RationalNumberType: "Precision of rational constants is limited to 4096 bits." (#3879)

`isImplicitlyCovertibleTo`

* [x] For rational literals that overflow target type: "Literal is too large to fit in [type]." (#6236)
* [x] For signed rational literals that are to be converted to unsigned types: "Cannot implicitly convert signed literal to unsigned type." (#6236)
* [x] For fixed point types that have too many fractional digits: "Too many fractional digits." (#6236)

--------
Pending cases

`binaryOperatorResult`

* [ ] ...

`isImplicitlyCovertibleTo`

* [ ] ...

**Comment by erak** [comment]
```
int a;
a = 4 ** 4 ** 2 ** 4 ** 4 ** 4 ** 4;
```
Result: ``Operator ** not compatible with types int_const 1797...(301 digits omitted)...7216 and int_const 4``

Suggested error: ``Resulting number exceeds precision of 4096 bit.``

**Comment by randomnetcat** [comment]
* [x] For rational literals that overflow target type: "Literal is too large to fit in [type]."
* [x] For signed rational literals that are to be converted to unsigned types: "Cannot implicitly convert signed literal to unsigned type."
* [x] For fixed point types that have too many fractional digits: "Too many fractional digits."

**Comment by chriseth** [comment]
What are places in the code where the condition for type conversion might be non-intuitive? Most of the forbidden type conversions are straightforward I guess.

**Comment by erak** [comment]
@chriseth Yes, in the compiler they are straightforward. I was under the impression that these improvements should rather help users to better understand why their code doesn't compile. And, of course, to validate if we even need ethereum/solidity#3879.

**Comment by chriseth** [comment]
I meant straightforward for the users.

Could you incorporate @meowingtwurtle's suggestions into a new PR? Yeah, I guess it does make sense after all to have #3879.

**Comment by ekpyron** [comment]
#4696 is another case that would have highly benefited from this.

**Comment by chriseth** [comment]
Is this actually done? Shouldn't we add more messages?

**Comment by Marenz** [comment]
Well, at least the ones listed here are added. But there is probably room for more, yes. Maybe a new ticket would be better for that though?

**Comment by chriseth** [comment]
I think the initial description is still clear, so I'll re-open.

**Comment by Marenz** [comment]
I very much disagree. For me it was a total mess to understand the current state of the ticket. I updated the initial comment now to provide a clear overview and status.
