### ISSUE TITLE
050 Breaking Features TODO list

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#4401]
I searched for 050 in libsolidity (latest develop) and these are the places that still mention it and should be worked on. Some of them already have PRs, so please edit this comment linking the PR to the task.

analysis/SyntaxChecker
- [x] Throw (@axic) #4481
- [x] UnaryOperation (add) (@christianparpart) #4408
- [x] Function visibility (@bit-shift) #4430 (blocked by #4403)
- [x] Old style constructor (@bit-shift) 1) #4402 2) #4215 
- [x] Functions without implementations cannot have modifiers (@christianparpart) #4411
- [x] Var keyword (@christianparpart) #4274 (ext: #4404)

analysis/StaticAnalyzer
- [x] msg.gas -> gasleft() #4410 #4423
- [x] block.blockhash -> blockhash() #4410 #4423

analysis/ViewPureChecker
- [x] Enforce view: #4409

analysis/ReferencesResolver
- [x] errorTypeForLoose (enforce error) (@christianparpart) #4412
- [x] data location must be specified (enforce error) (@ekpyron) #4478

analysis/TypeChecker
- [x] Fallback function must be defined as external: @christianparpart #4376
- [x] Modifier-style base constructor call without arguments (enforce error): https://github.com/ethereum/solidity/pull/4378
- [x] Base constructor arguments given twice (enforce error): #4379
- [x] Wrong argument count for constructor call (enforce error): #4454
- [x] Functions in interfaces must be declared external (enforce error) @christianparpart #4500
- [x] Initial value for constant variable (enforce error): https://github.com/ethereum/solidity/pull/4418
- [x] errorTypeForLoose (enforce error): @christianparpart #4412
- [x] Uninitialized storage pointer (enforce error) (@ekpyron) #4415
- [x] Different number of components in declaration (enforce error) (@ekpyron) #4431
- [x] Different number of components in assignment (enforce error) @expyron #4465
- [x] Tuple component cannot be empty (enforce error): @ekpyron
- [x] Cannot perform packed encoding for a literal (enforce error): https://github.com/ethereum/solidity/pull/4388
- [x] Convert the contract to address type to access the member (depends on #4438 and #4439)
- [x] Hexadecimal numbers cannot be used with unit denominations (enforce error): #4440
- [x] Remove any trace of type inference from `visit(VariableDeclarationStatement const&)` @christianparpart #4507

ast/ExperimentalFeatures
- [x] Remove 050 experimental feature

ast/Types
- [x] Non conflicting address members #4439 

ast/ExpressionCompiler
- [x] Static call: #4428

**Comment by chriseth** [comment]
Still needs https://github.com/ethereum/solidity/pull/4738

**Comment by axic** [comment]
All of those are in the project. Do not see much point for this issue :)

**Comment by chriseth** [comment]
But the boxes are not all ticked!

**Comment by chriseth** [comment]
Ok, changed the list.
