### ISSUE TITLE
Strict fallback handling

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#562]
I think it time to consider adding more safety mechanisms into Solidity. One good candidate is cleaning up the handling of the fallback method.

Situation now:
- If no fallback is defined in Solidity, the contract just returns.
- If a fallback is defined it is executed.

I propose the following:

1) Keyword to enable the fallback method: `fallback`.  A fallback body declaration is mandatory.

```
contract Test fallback {
}
```

2) A contract without the `fallback` keyword should fail compilation if the fallback method is present.

3) If no fallback is defined and no matching ABI signature is found, the contract should `throw`.

4) A library cannot have the `fallback` keyword.

5) Regarding the appropriate interface JSON, please see https://github.com/ethereum/solidity/issues/499
## 

Remark about input/output parameters to the fallback method:

1) Right now the language won't accept method parameters, but that can be circumvented by the user with using `msg.data`

2) Right now it allows defining return parameters which are encoded using the ABI. According to @chriseth this is unwanted. If it is removed, I would propose adding an option to return raw data by a singular `bytes` return value (which won't include the size field). Update: see #15, which proposes the same change.

**Comment by chriseth** [comment]
I would like to simplify this to:
- the "default implementation" of the fallback function throws
- libraries cannot have fallback functions

Having the keyword and the function present is basically the same thing expressed in two ways.

**Comment by axic** [comment]
@chriseth: Well my current view on this, given all the other changes, is:
- [x] there's no fallback defined by default and the contract throws if no matching signature is found (fixed in #954)
- [x] if a fallback method is defined, it can be executed
- [x] fallback must be defined in the ABI JSON (fixed in #664)
- [x] fallback cannot have return values (fixed in #949)
- [x] fallback cannot have the `constant` modifier (fixed in #963 / #1014 )
- [x] libraries cannot have fallback functions (fixed in #954)
- [x] a fallback method needs to have the `payable` modifier if they want to receive ether
