### ISSUE TITLE
Support for Istanbul

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7310]
For an accurate list of changes see [EIP-1679](https://eips.ethereum.org/EIPS/eip-1679).

Valid as of today:
- EIP-152: Add Blake2 compression function F precompile
- EIP-1108: Reduce alt_bn128 precompile gas costs
- EIP-1344: Add ChainID opcode
- EIP-1884: Repricing for trie-size-dependent opcodes
- EIP-2028: Calldata gas cost reduction
- EIP-2200: Rebalance net-metered SSTORE gas cost with consideration of SLOAD gas cost change

Changes needed in Solidity:
- [x] Add Istanbul EVMVersion [#7329]
- [x] Add `chainid` opcode [#7327]
- [x] Add `selfbalance` opcode [#7327]
- [x] Make use of `selfbalance` opcode.
- [x] Reprice call data (EIP-2028), `sstore` (EIP-2200), `sload`/`balance`/`extcodehash` (EIP-1884), bn128 precompiles (in tests) (EIP-1108) [#7740]
- [x] Update evmc/evmone [#7655]

Please note that evmone currently doesn't implement any of the Istanbul changes and the breaking EVMC7 release is required for Istanbul support.
