### ISSUE TITLE
[Sol - Yul] Support (in-memory) structs properly

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8085]
```
contract C {
  struct S {
    uint a;
  }
  
  function f() external {
    S memory s;
    s.a = 1;
  }
}
```

```
contract C {
  struct S {
    uint a;
  }
  S s;
  
  function f() external {
    s.a = 1;
  }
}
```

```
contract C {
  struct S {
    uint a;
  }
  mapping (uint => S) m;
  
  function f() external {
    S memory s;
    m[1] = s;
  }
}
```

```
contract C {
  struct S {
    uint a;
  }
  
  function f() external {
    S memory s = S(1);
  }
}
```

**Comment by chriseth** [comment]
This includes:
 - [x] memory struct creation
 - [x] member access to memory structs
 - [ ] copying from storage to memory (#9602)
 - [ ] copying from memory to storage (#9602)
 - [x] copying from calldata to memory (#9503)
 - [x] member access for calldata structs (#9177)

**Comment by Marenz** [comment]
I've started work on memory struct creation

**Comment by mijovic** [comment]
I am working on copying between storage and memory

**Comment by chriseth** [comment]
All examples compile now.
