### ISSUE TITLE
[Fuzzing] Write a semantic fuzzer for testing Solidity inheritance rules 

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#8636]
## Abstract

Goal is to write a grammar based fuzzer that automatically generates tests like

```
contract C {
  function test() public pure returns (uint) {
    C1 testContract = new C1();
    if (testContract.f() != 1337)
      return 1;
    return 0;
  }
}

abstract contract C2 {
  function f() public pure virtual returns (uint);
}

contract C1 is C2 {
  function f() override public pure returns (uint) {
    return 1337;
  }
}
```

The workflow is
  - Libprotobufmutator generates a new test instance (protobuf based)
  - test instance is translated to Solidity code
  - Solidity code is executed on evmone
  - Output of evmone is asserted to `0`.

## Motivation

Split into following easily reviewable PRs
  - [x] Permit linking libraries in compilation framework used by fuzzer code (#8705)
  - [ ] Add a protobuf specification for inheritance fuzzer and a skeleton converter (#8706 )
  - [ ] Add a test harness for the fuzzer (#8708)
  - [ ] Add an intermediate representation (adaptor) to easily convert from protobuf spec to solidity code
