### ISSUE TITLE
Compile the "eth2-deposit-contract" with the IR

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8853]
This is a tracking issue for the non-official deposit contract: https://github.com/axic/eth2-deposit-contract

- [x] Constants #8344 / #8718
- [x] sha256 #8720
- [x] Shift right #8719
- [x] `abi.encodePacked` #8799
- [x] `new bytes(n)` #8937
- [x] ~~Calldata to memory copying (`bytes(slice[:32])`) #8844~~ It seems to be compiling without this (because likely `sha256(bytes(signature[:64]))` handles it)
- [x] Fails on `IRGeneratorForStatements.cpp(1775)` `!isBareCall`. #8841 
- [x] Exp binary operation #9110
- [x] Indexing of `bytes8` #9109

**Comment by axic** [comment]
This works now with https://github.com/axic/eth2-deposit-contract/releases/tag/r2 (must remove the version pragma though).

Well, the resulting IR (even with `--ir-optimized`) results in out of stack, but we are one step closer:
```
Exception while assembling: /Users/alex/Projects/solidity/libyul/backends/evm/EVMObjectCompiler.cpp(66): Throw in function void solidity::yul::EVMObjectCompiler::run(solidity::yul::Object &, bool)
Dynamic exception type: boost::wrapexcept<solidity::yul::StackTooDeepError>
std::exception::what: Variable vloc_signature_206_offset is 3 slot(s) too deep inside the stack.
[solidity::util::tag_comment*] = Variable vloc_signature_206_offset is 3 slot(s) too deep inside the stack.

```
