### ISSUE TITLE
[Sol -> Yul] Support array copying 

### ISSUE THREAD

**Issue by mijovic** [ethereum/solidity#9725]
`bytes` array is missing:
- [x] Calldata to storage (#10083)
- [x] Memory to storage (#10083)
- [x] Storage to memory
- [x] Storage to storage

Dynamic arrays are missing these:
- [x] Calldata to storage
- [x] Calldata to memory (#10211)
- [x] Memory to storage
- [x] Storage to memory
- [x] Storage to storage

**Comment by mijovic** [comment]
I think we covered all cases now
