### ISSUE TITLE
[SMTChecker] Validate the eth2 deposit contract

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9806]
https://github.com/axic/eth2-deposit-contract/blob/master/deposit_contract.sol

It would be nice to be able to "verify" the deposit contract, or at least to remove the warnings for unimplemented features.

- [x] checked arithmetic https://github.com/ethereum/solidity/issues/10066
- [x] in place constants https://github.com/ethereum/solidity/issues/10631
- [x] `type(T).max` (#9780)
- [x] `type(I).interfaceId` (#9781)
- [x] type conversions with literals (e.g. `bytes24(0)`) (#9789)
- [x] truncating type conversions (e.g. `uint64(deposit_count)` where `deposit_count` is `uint256`) (#5808 #5795)
- [x] indexed access of fixed bytes (#7663)
- [x] memory allocation (`new bytes()`) (#6050)
- [x] abi.encodePacked (#5264)
- [x] sha256 https://github.com/ethereum/solidity/issues/9908
- [x] bytes slices (e.g. `signature[64:]`) (#9885)
- [x] constants (#8669)
- [x] events (#9785)
- [x] Handle `return` properly (https://github.com/ethereum/solidity/issues/9103)

---

For reference, this is the status as of Oct 17 (source was modified to remove the constant):
```
Warning: Assertion checker does not yet implement this type of function call.
  --> deposit_contract_r2.sol:87:31:
   |
87 |                 node = sha256(abi.encodePacked(branch[height], node));
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
  --> deposit_contract_r2.sol:89:31:
   |
89 |                 node = sha256(abi.encodePacked(node, zero_hashes[height]));
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
  --> deposit_contract_r2.sol:92:23:
   |
92 |         return sha256(abi.encodePacked(
   |                       ^ (Relevant source part starts here and spans across multiple lines).

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:131:38:
    |
131 |         bytes32 pubkey_root = sha256(abi.encodePacked(pubkey, bytes16(0)));
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:133:20:
    |
133 |             sha256(abi.encodePacked(signature[:64])),
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:134:20:
    |
134 |             sha256(abi.encodePacked(signature[64:], bytes32(0)))
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:132:41:
    |
132 |         bytes32 signature_root = sha256(abi.encodePacked(
    |                                         ^ (Relevant source part starts here and spans across multiple lines).

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:137:20:
    |
137 |             sha256(abi.encodePacked(pubkey_root, withdrawal_credentials)),
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:138:20:
    |
138 |             sha256(abi.encodePacked(amount, bytes24(0), signature_root))
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:136:31:
    |
136 |         bytes32 node = sha256(abi.encodePacked(
    |                               ^ (Relevant source part starts here and spans across multiple lines).

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:155:27:
    |
155 |             node = sha256(abi.encodePacked(branch[height], node));
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: BMC: Assertion violation might happen here.
   --> deposit_contract_r2.sol:160:9:
    |
160 |         assert(false);
    |         ^^^^^^^^^^^^^
Note: 
Note that some information is erased after the execution of loops.
You can re-introduce information using require().

Warning: Assertion checker does not yet implement this type of function call.
  --> deposit_contract_r2.sol:79:46:
   |
79 |             zero_hashes[height + 1] = sha256(abi.encodePacked(zero_hashes[height], zero_hashes[height]));
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

And with the "constant" put back in place:
```
Warning: Assertion checker does not yet implement this type of function call.
  --> deposit_contract_r2.sol:87:31:
   |
87 |                 node = sha256(abi.encodePacked(branch[height], node));
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
  --> deposit_contract_r2.sol:89:31:
   |
89 |                 node = sha256(abi.encodePacked(node, zero_hashes[height]));
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
  --> deposit_contract_r2.sol:92:23:
   |
92 |         return sha256(abi.encodePacked(
   |                       ^ (Relevant source part starts here and spans across multiple lines).

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:131:38:
    |
131 |         bytes32 pubkey_root = sha256(abi.encodePacked(pubkey, bytes16(0)));
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:133:20:
    |
133 |             sha256(abi.encodePacked(signature[:64])),
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:134:20:
    |
134 |             sha256(abi.encodePacked(signature[64:], bytes32(0)))
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:132:41:
    |
132 |         bytes32 signature_root = sha256(abi.encodePacked(
    |                                         ^ (Relevant source part starts here and spans across multiple lines).

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:137:20:
    |
137 |             sha256(abi.encodePacked(pubkey_root, withdrawal_credentials)),
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:138:20:
    |
138 |             sha256(abi.encodePacked(amount, bytes24(0), signature_root))
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:136:31:
    |
136 |         bytes32 node = sha256(abi.encodePacked(
    |                               ^ (Relevant source part starts here and spans across multiple lines).

Warning: Assertion checker does not yet implement this type of function call.
   --> deposit_contract_r2.sol:155:27:
    |
155 |             node = sha256(abi.encodePacked(branch[height], node));
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: BMC: Assertion violation might happen here.
   --> deposit_contract_r2.sol:160:9:
    |
160 |         assert(false);
    |         ^^^^^^^^^^^^^
Note: 
Note that some information is erased after the execution of loops.
You can re-introduce information using require().

Warning: Assertion checker does not yet implement this operator.
  --> deposit_contract_r2.sol:68:39:
   |
68 |     uint constant MAX_DEPOSIT_COUNT = 2**DEPOSIT_CONTRACT_TREE_DEPTH - 1;
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Assertion checker does not yet implement this type of function call.
  --> deposit_contract_r2.sol:79:46:
   |
79 |             zero_hashes[height + 1] = sha256(abi.encodePacked(zero_hashes[height], zero_hashes[height]));
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: BMC: Underflow (resulting value less than 0) happens here.
  --> deposit_contract_r2.sol:68:39:
   |
68 |     uint constant MAX_DEPOSIT_COUNT = 2**DEPOSIT_CONTRACT_TREE_DEPTH - 1;
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: Counterexample:
  <result> = (- 115792089237316195423570985008687907853269984665640564039457584007913129639936)
  DEPOSIT_CONTRACT_TREE_DEPTH = 32
  MAX_DEPOSIT_COUNT = 0
  deposit_count = 0
  height = 0

Note: Callstack:
Note: 
Note that some information is erased after the execution of loops.
You can re-introduce information using require().


```

**Comment by leonardoalt** [comment]
All the features were merged!

I'd still keep this issue open, because:

The SMTChecker creates a bunch of verification targets: `assert(false)` and some arithmetic checks. Unfortunately I don't think we'll be able to prove that `assert(false)` is unreachable, because this requires Spacer to infer a nonlinear invariant for the loop, which I don't think will happen.

However, it should be able to prove the arithmetic checks. Right now it's not able to, for any of them.
My analysis is that currently it cannot prove termination of the loop, which blocks the inductiveness of the safe arithmetic properties. Proving termination of the loop should be easy though: even if `return` is never reached, the loop has at most 32 iterations, so it should be able to ainfer that the loop can at least run entirely and go on with the function (reaching assert(false)).
Currently, it's not. Constants are still a problem. Even though the constant is assigned at deployment, it needs to be "carried over" by the predicates, and this information is lost at some point. Spacer has some new work fixing that, but it won't be available until z3's next version. One easy fix one our side that makes sense anyway is replacing the constants by their values in place, like the code generator does. Another small but annoying issue is wrapping arithmetic inside loops (`height++`). This should be fixed by supporting checked arithmetic.

**Comment by leonardoalt** [comment]
Running current develop on vanilla `deposit.sol` proves all targets but the `assert`, which is actually the best we can expect due to the `assert(false)` needing a nonlinear inductive invariant which we don't expect Spacer to find. All the language features are supported.
